services:
  - type: web
    name: cash-loan-frontend
    runtime: node
    plan: free
    region: oregon
    branch: main
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.19.5
      - key: NEXT_PUBLIC_API_URL
        sync: false
